---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: flask-app-dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s