---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app-dev
spec:
  type: LoadBalancer
  selector:
    app: flask-app-dev
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 5000